# Vector Addition: Array vs Lists

In [13]:
list_two = list(range(1, 4))
list_three = list(range(1, 4))
list_sum = []

list_sum = [x**2 + y**3 for x,y in zip(list_two, list_three)]
print(list_sum)
list_sum = []

[2, 12, 36]


In [14]:
for index in range(3):
    list_two[index] = list_two[index]**2
    list_three[index] = list_three[index]**3
    list_sum.append(list_two[index] + list_three[index])
print(list_sum)

[2, 12, 36]


In [5]:
import numpy as np
array_two = np.arange(1,4) ** 2
array_three = np.arange(1,4) ** 3
print(array_two + array_three)

[ 2 12 36]


In [8]:
print(np.power(np.array([1, 2, 3]), 4))

[ 1 16 81]


In [9]:
print(np.negative(np.array([1, 2, 3])))

[-1 -2 -3]


In [10]:
print(np.exp(np.array([1, 2, 3])))

[ 2.71828183  7.3890561  20.08553692]


In [12]:
print(np.log(np.array([1, 2, 3])))

[0.         0.69314718 1.09861229]


In [13]:
print(np.sin(np.array([1, 2, 3])))

[0.84147098 0.90929743 0.14112001]


# Multidimensional Arrays:

In [28]:
x = np.arange(3)
y = np.arange(3)
z = np.arange(3)
multi_array = np.array([x,y,z], dtype = np.int16)
print(multi_array)
print(multi_array.shape)

[[0 1 2]
 [0 1 2]
 [0 1 2]]
(3, 3)


In [21]:
w = np.linspace(0, 10, 20)
print(w)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [25]:
b = np.linspace(0, 10, 10)
print(b)

[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]


In [26]:
multi_array[1,2]

2

In [29]:
print(multi_array.dtype)

int16


# Slicing:

In [31]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [33]:
print(x[2:7])
print(x[2:8:3])

[2 3 4 5 6]
[2 5]


# Reshaping:

In [44]:
x = np.arange(12).reshape(3, -1)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [49]:
x = np.arange(18).reshape(3, 2, 3)
print(x)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]


# Multidimensional Slicing:

In [51]:
print(x[1,1,1])

10


In [57]:
x[1, :2, :3]

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [60]:
x[:3, 0, 0]

array([ 0,  6, 12])

In [61]:
x[x > 5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [63]:
x.max()

17

In [64]:
x.min()

0

# Manipulating Array Shapes:

In [67]:
x = np.arange(9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2 3 4 5 6 7 8]


In [72]:
ravelled_array = x.ravel()
ravelled_array[2] = 100
print(ravelled_array)
print(x)

[  0   1 100   3   4   5   6   7   8]
[[  0   1 100]
 [  3   4   5]
 [  6   7   8]]


In [74]:
flattened_array = x.flatten()
flattened_array[3] = 95
print(flattened_array)
print(x)

[  0   1 100  95   4   5   6   7   8]
[[  0   1 100]
 [  3   4   5]
 [  6   7   8]]


In [78]:
y = np.arange(9)
y.shape = [3,3]
print(y)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [80]:
print(y.transpose())
print(y.T)

[[0 3 6]
 [1 4 7]
 [2 5 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [81]:
print(np.resize(y, (6, 6)))

[[0 1 2 3 4 5]
 [6 7 8 0 1 2]
 [3 4 5 6 7 8]
 [0 1 2 3 4 5]
 [6 7 8 0 1 2]
 [3 4 5 6 7 8]]


In [91]:
print(np.zeros((3,2), dtype = int))

[[0 0]
 [0 0]
 [0 0]]


In [94]:
print(np.ones((2,3), dtype = int))

[[1 1 1]
 [1 1 1]]


In [98]:
print(np.eye(5, dtype = int))

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [99]:
np.random.rand(3,2)

array([[0.51435464, 0.48194513],
       [0.80737937, 0.29591025],
       [0.00398929, 0.02574952]])

# Matrix Multiplication:

In [101]:
mat_a = np.matrix([0, 3, 5, 5, 5, 2]).reshape(2, 3)
print(mat_a)

[[0 3 5]
 [5 5 2]]


In [102]:
mat_b = np.matrix([3, 4, 3, -2, 4, -2]).reshape(3, 2)
print(mat_b)

[[ 3  4]
 [ 3 -2]
 [ 4 -2]]


In [103]:
print(mat_a * mat_b)

[[ 29 -16]
 [ 38   6]]


In [105]:
print(np.matmul(mat_a, mat_b))

[[ 29 -16]
 [ 38   6]]


In [106]:
print(mat_a @ mat_b)

[[ 29 -16]
 [ 38   6]]


# Stacking:

In [131]:
x = np.arange(4).reshape(2,2)
print(x)

[[0 1]
 [2 3]]


In [132]:
y = np.arange(4, 8).reshape(2, 2)
print(y)

[[4 5]
 [6 7]]


In [128]:
depth_stack = np.dstack((x,y))
print(depth_stack)
print(depth_stack.shape)

[[[0 4]
  [1 5]]

 [[2 6]
  [3 7]]]
(2, 2, 2)


In [129]:
z = np.hstack((x, y))
print(z)
print(z.shape)

[[0 1 4 5]
 [2 3 6 7]]
(2, 4)


In [134]:
print(np.column_stack((x, y)))

[[0 1 4 5]
 [2 3 6 7]]


In [120]:
print(np.concatenate((x, y), axis = 1 ))

[[0 1 4 5]
 [2 3 6 7]]


In [135]:
x = np.arange(8).reshape(2,4)
print(x)

[[0 1 2 3]
 [4 5 6 7]]


In [136]:
y = np.arange(8, 20).reshape(3, 4)
print(y)

[[ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [123]:
z = np.vstack((x, y))
print(z)
print(z.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
(5, 4)


In [137]:
print(np.row_stack((x,y)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [124]:
print(np.concatenate((x, y), axis = 0 ))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
